//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AP_FinalProject_4002
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDFBooksTable
    {
        public int ID { get; set; }
        public string name { get; set; }
        public string authorName { get; set; }
        public long cost { get; set; }
        public string summary { get; set; }
        public int point { get; set; }
        public bool bookType { get; set; }
        public long off { get; set; }
        public Nullable<System.DateTime> offTime { get; set; }
        public string photoPath { get; set; }
        public string PDF_FileName { get; set; }
        public int publishYear { get; set; }
        public long outcome { get; set; }
        public int numberOfSoldBooks { get; set; }
        public long monthlySubscriptionFee { get; set; }
        public System.DateTime authorBirthDay { get; set; }
        public bool authorGender { get; set; }
        public string authorBooks { get; set; }
        public string authorNationality { get; set; }
    }
}
